### ISSUE TITLE
Ajouter un bouton idle

### ISSUE THREAD

**Issue by MatthieuMota** [WebforceLille8/BeerParty#11]
On doit avoir un bouton sur chaque bière qui nous permet d'incrémenter la valeur de +1 pour la bière actuelle. L'information doit être stockée dans le storage. Il faut trouver un moyen pour que l'incrémentation soit de plus en plus longue avec une barre de progression par exemple.

**Comment by tr-adubois** [comment]
Je veux bien prendre.
