### ISSUE TITLE
Créer la page Contact

### ISSUE THREAD

**Issue by MatthieuMota** [WebforceLille8/BeerParty#6]
Formulaire avec un champs sujet et message.
Le sujet ne doit pas être vide et le message doit faire 10 caractères minimum.
Quand on clique sur envoyer, le formulaire disparait et un message "Message bien envoyé" apparaît à la place.
Voir avec @Thomas-Ringot pour la librairie

**Comment by deswelle-j** [comment]
J'ai créé la page et l'ai mise en lien dans le menu.
